### PR TITLE
Rob H - streak feature

### PR DESCRIPTION
**Pull request by robhewison**
added a streak ui element flame that appears in the header of every page, the streak is supposed to increment by 1 each day that the user logs into the app

Issue #39

### CODE REVIEW

**Comment by esnowgol** [comment]
Looks good! Some tweaks on the login needed that we talked about, but that's it

**Comment by esnowgol** [comment]
As we discussed, the token needs to be set on sign up, after that sign up is fixed to use our tokens

Additionally, there's a warning that a currently used prop will be removed in a future major release. For now, it works, and we can try to fix that warning in the next sprint if we have time.

**Review by esnowgol — APPROVED** [review]
Looks good! Excited to get some real data in these graphs!

**Comment by sjiang1** [comment]
Quality of Code: Good
Participation in Code Review: Good
Post-Review Changes: Good

(-2 pts): The pull request description needs more details.
(-2 pts): Some commit messages do not follow the required format outlined in the lecture.

**Pull request merged**
