### PR TITLE
Start workouts page issue 13

### PR DESCRIPTION
**Pull request by MichaelSH7**
1. removed timer feature for now may add back later
2. added a custom way to add exercise to log
3. am able to edit those changes
4. suggested exercise buttons
5. need to add a savable feature
issue #13

### CODE REVIEW

**Comment by esnowgol** [comment]
Looks amazing already, I'm really impressed. Fantastic job.

Only other steps I can think of that could be good are data input validation - Max Sets and Reps to ~1000 or something. Nobody is doing that many, but prevents ridiculously long numbers

For Reps/Sets, prevent the user from adding "1-5" (one dash five) or "1.5" as inputs

**Comment by hoangnatalie** [comment]
This is an amazing screen, great work!
Highlights: The colors chosen are nice and the modal is a cool feature.
Feedback/suggestions: For the suggested exercises, make sure to keep it consistent with the capitalization. Some exercises in the list aren't capitalized (Cable row, calf raises, Rear delt flys). Also, the header title should be changed to include spaces and drop the screen part.

**Review by esnowgol — APPROVED** [review]
Amazing job, looks really good.

Has some difficulty on android with lower textboxes, but this can be addressed next Sprint

**Comment by sjiang1** [comment]
Quality of Code: Good
Participation in Code Review: Good
Post-Review Changes: Good

**Pull request merged**
