### PR TITLE
Natalie/Welcome pages

### PR DESCRIPTION
**Pull request by hoangnatalie**
# Welcome Pages

## Description:

Created the welcome pages - welcome, login, signup. The user will see the welcome page first. Then they will have the option to go to the login or signup page

## Key Changes:

- Implemented 3 screens
- Each screen has a similar layout to each other.
- The login and signup both have a button to navigate to the other.
- Input boxes for password has text hidden and a toggle to view password.

## What’s Not Completed (Non UI): 

- Login and signup handling 
- Error message display

## Testing Instructions:

- Screen description text have the correct info
- Buttons have the correct titles
- Buttons go to the correct page
- Posts should display in chronological order.
- 
Issue #9

### CODE REVIEW

**Comment by hoangnatalie** [comment]
Note: I did NOT remove the directory called "main" in the backend/src/test folder!

**Comment by esnowgol** [comment]
Looks really good!

You can still navigate backwards back to login/signup after making it to mainApp, I believe we previously talked about it

If in your login screen and sign-up screen, you add this:

  ```
const navigateToMainApp = () => {
    navigation.reset({
      index: 0,
      routes: [{ name: 'Home' }],  // Only 'Home' will be in the stack
    });
  };
```
  
  then use:
`  onPress={()  => navigateToMainApp()}`
  
  Instead of 
  `onPress={() => navigation.navigate('Home')}`
  
  This approach seems to prevent that, and may be more in line with your goals. Mine instead of going back to login page, exits the app. We may be able to do what other apps I've seen do: Send a Toast message that says "Press back one more time to exit the app" or similar. However I'm not sure if IOS has a equivalent to android's Toast message
  
  
image

**Review by esnowgol — APPROVED** [review]
Looks great, works great, and tests pass, nice job!

**Comment by robhewison** [comment]
The code and pages overall look very good! It seems you have a good separation of concerns in your code which is good coding style. You also made good use of having reusable components like CustomButton and CustomTextInput. Some of the <View> containers in LoginScreen and SignupScreen seem a bit unnecessary especially when they wrap around only a single element like the Logo for example. There is a lot of commented out style code, if the code is no longer needed you could get rid of it to improve readability. Also the CustomButton in your WelcomeScreen has a fixed value of 210 while the LoginScreen and the SignupScreen don't have a fixed width and use ```const { width } = Dimensions.get('window');```

Overall the code is really good and my critiques are pretty minor things. I really like the design of it.

**Pull request merged**
