### PR TITLE
Frontend | Notes Screen

### PR DESCRIPTION
**Pull request by hoangnatalie**
This commit added the notes screen (no functionality) and fixed some headers on a couple pages. Currently, the note "buttons" do not go to an edit note page.

Issue #42

### CODE REVIEW

**Comment by esnowgol** [comment]
Looks great! I really like the Sticky Note colors used.

MyWorkoutsScreen also has a search bar already. Not sure which we would prefer, but I'd recommend tweaking the style of one so they're consistent across the app

**Comment by hoangnatalie** [comment]
Future:
Add a notes table to database.
Connect notes to database instead.
Be able to save notes depending on user.

**Comment by robhewison** [comment]
The feature looks pretty good, but I noticed a bug with the date where it overhangs outside of the note on the My Notes page. Also when I'm writing within the body field it's hard to click out and be able to click on the "save note" button at the bottom of the screen. In order to close the keyboard I need to click on the title then click return. 

The code is overall very well written, the code has a good separation of concerns. It's also written in a very well maintainable way. 

Overall I like the design! Good job!

**Comment by esnowgol** [comment]
I noticed the same as Rob. If in Note.tsx for button you replace:
height: 125
with
flex:1

Then the note will resize to fit the text properly

I've also made some changes to enable 2 columns similar to the mockup that we can discuss

**Review by esnowgol — APPROVED** [review]
Great Job! Looks really nice

**Comment by sjiang1** [comment]
Quality of Code: Good
Participation in Code Review: Good
Post-Review Changes: Good

(-2 pts): The pull request description needs more details.

**Pull request merged**
